### ISSUE TITLE
Gridcoin trading on Poloniex down for months now.

### ISSUE THREAD

**Issue by gettingmad** [gridcoin/Gridcoin-Research#1023]
I have been waiting for months for a deposit of over 2000 GRC to Poloniex that is still pending your fix. This IS an issue. Are you going to fix it? Ever?

**Comment by grctest** [comment]
All exchanges have been notified to open again since the fixes have been applied & new fixes for Bittrex developed. Poloniex is notorious for slow response & they've just been bought by Circle so expect further delays from Poloniex (not us).

**Comment by dc7dgrid** [comment]
Trading is NOT down, only deposit/withdrawal

**Comment by RoboticMind** [comment]
Can we close this @denravonska ?
