### ISSUE TITLE
McAfee Detect virus in gridcoin-5.3.2-win64-setup.exe

### ISSUE THREAD

**Issue by Houmer121** [gridcoin/Gridcoin-Research#2301]
McAfee antivirus  blocked download and run of file "gridcoin-5.3.2-win64-setup.exe"

MaAfee Endpoint security 10.7.
McAfee agent 5.6.1.308
![Virus detect](https://user-images.githubusercontent.com/89508558/130741232-f1cc9398-0a68-4d5c-b1e3-832c9396e952.jpg)

**Comment by jamescowens** [comment]
Cryptocurrencies are often flagged as adware by antivirus programs. Gridcoin is no exception. There is no virus or malware in the official release versions provided on the GitHub download link. You may have to make an exception in your antivirus program.

**Comment by Houmer121** [comment]
OK, I wrote it because the previous version did not have this problem ...

**Comment by iFoggz** [comment]
They are updating the database regularly. All it has to do is come by them once and see its' crypto related and it will be added as a Potentially unwanted program. If there was any kind of threat per say it would specify the threat but as you can see in the picture there is no specific threat only a potentially unwanted program. Its unfortunate they group multiple categories together.
