### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin/Gridcoin-Research#742]
Вместо gridcoin написано gricoin
![9](https://user-images.githubusercontent.com/8822292/33208928-ad3cf104-d124-11e7-9234-0260569bc49b.png)

**Comment by tomasbrod** [comment]
> Instead of "gridcoin" it reads "gricoin" (missing letter _d_).

Is this specific to russian locale or happens with english translation as well?

**Comment by kotenok2000** [comment]
It is specific to russian locale.

**Comment by denravonska** [comment]
Fixed.
