### ISSUE TITLE
Galaza doesn't start.

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin/Gridcoin-Research#918]
[galaza log.txt](https://github.com/gridcoin/Gridcoin-Research/files/1692075/galaza.log.txt)
When i try to start the game it crashes

**Comment by gridcoin** [comment]
I cant see what language you are in Kotenok, but it looks like the windows media files are missing.
These are wav files such as "bgm.wav" (background music wav file) and abducted.wav (ship being abducted).

I dont see these files in the commit.

Try downloading them from here, and place these wav files in your \bin directory (wherever galaza.exe is located):

https://github.com/RUB-NDS/Gridcoin-Attacks/tree/master/contrib/Installer/GridcoinRDTestHarness/GridcoinRDTestHarness/bin/Galaza



Good luck,

Rob

**Comment by kotenok2000** [comment]
It didn't help.
Maybe is is because i use 64 bit windows?

**Comment by gridcoin** [comment]
Galaza is unsupported.

**Comment by barton2526** [comment]
#945
